services:
  nmgsoft:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nmgsoft
    restart: unless-stopped
    ports:
      - "3010:3000"
    networks:
      - web-proxy-net

networks:
  web-proxy-net:
    external: true
